#!/bin/sh

typ="$(type $@ 2>/dev/type)"
if [[ "$typ" != "" ]];then
  busca_ruta="$(echo "$typ" | grep "/" 2>/dev/null)"
  if [[ "$busca_ruta" != "" ]];then
    ruta="$(echo "$busca_ruta" | sed -r "s/([^/]*)(\/.*)/\2/g")"
    l="$(ldd "$ruta" 2>/dev/ldd)"
    d="$(cat /dev/ldd)"
    if [[ "$d" != "	no es un ejecutable dinámico"
       && "$d" != "	not a dynamic executable"
    ]];then
      #echo "'$(cat /dev/ldd)'"
      echo "$l"
    else
      cat "$ruta"
    fi
  fi
fi
